// Generated by https://quicktype.io

import { ReleaseDefinition } from "./release-definition";

export interface Release {
    id: number;
    name: string;
    status: string;
    createdOn: string;
    modifiedOn: string;
    modifiedBy: IdentityRef;
    createdBy: IdentityRef;
    createdFor: IdentityRef;
    variables: Properties;
    variableGroups: any[];
    releaseDefinition: ReleaseDefinition;
    releaseDefinitionRevision: number;
    description: string;
    reason: string;
    releaseNameFormat: string;
    keepForever: boolean;
    definitionSnapshotRevision: number;
    logsContainerUrl: string;
    url: string;
    _links: ReleaseLinks;
    tags: any[];
    triggeringArtifactAlias: null;
    projectReference: ProjectReference;
    properties: Properties;
}

export interface ReleaseLinks {
    self: ResourceReference;
    web:  ResourceReference;
}

export interface ResourceReference {
    href: string;
}

export interface IdentityRef {
    displayName: string;
    url:         string;
    _links:      IdentityLinks;
    id:          string;
    uniqueName:  string;
    imageUrl:    string;
    descriptor:  string;
}

export interface IdentityLinks {
    avatar: ResourceReference;
}

export interface ProjectReference {
    id:   string;
    name: string;
}

export interface Properties {
}
