// Generated by https://quicktype.io

import { IdentityRef, ResourceReference } from "./release";

export interface ReleaseDefinition {
    source:            string;
    id:                number;
    revision:          number;
    name:              string;
    description:       null;
    createdBy:         IdentityRef;
    createdOn:         string;
    modifiedBy:        IdentityRef;
    modifiedOn:        string;
    lastRelease:       LastRelease;
    path:              string;
    variableGroups:    null;
    releaseNameFormat: string;
    url:               string;
    _links:            Links;
    properties:        Properties;
}

export interface Links {
    self: ResourceReference;
    web:  ResourceReference;
}

export interface LastRelease {
    id:                number;
    name:              string;
    artifacts:         any[];
    webAccessUri:      null;
    _links:            Properties;
    description:       string;
    releaseDefinition: ReleaseDefinitionLinks;
    createdOn:         string;
    createdBy:         IdentityRef;
    modifiedBy:        null;
    reason:            string;
}

export interface Properties {
}

export interface ReleaseDefinitionLinks {
    id:     number;
    _links: Properties;
}
