// Generated by https://quicktype.io

import { IdentityRef, ResourceReference } from "./release";

export interface WorkItemDetail {
    id:                number;
    rev:               number;
    fields:            FieldsClass;
    relations:         Relation[];
    commentVersionRef: CommentVersionRef;
    _links:            WorkItemDetailLinks;
    url:               string;
}

export interface WorkItemDetailLinks {
    self:              ResourceReference;
    workItemUpdates:   ResourceReference;
    workItemRevisions: ResourceReference;
    workItemComments:  ResourceReference;
    html:              ResourceReference;
    workItemType:      ResourceReference;
    fields:            ResourceReference;
}

export interface CommentVersionRef {
    commentId: number;
    version:   number;
    url:       string;
}

export interface FieldsClass {
    "System.AreaPath":                       string;
    "System.TeamProject":                    string;
    "System.IterationPath":                  string;
    "System.WorkItemType":                   string;
    "System.State":                          string;
    "System.Reason":                         string;
    "System.AssignedTo":                     IdentityRef;
    "System.CreatedDate":                    string;
    "System.CreatedBy":                      IdentityRef;
    "System.ChangedDate":                    string;
    "System.ChangedBy":                      IdentityRef;
    "System.CommentCount":                   number;
    "System.Title":                          string;
    "Microsoft.VSTS.Common.StateChangeDate": string;
    "Microsoft.VSTS.Common.ActivatedDate":   string;
    "Microsoft.VSTS.Common.ActivatedBy":     IdentityRef;
    "Microsoft.VSTS.Common.ClosedDate":      string;
    "Microsoft.VSTS.Common.ClosedBy":        IdentityRef;
    "Microsoft.VSTS.Common.Priority":        number;
    "System.History":                        string;
    "System.Parent":                         number;
}

export interface Relation {
    rel:        string;
    url:        string;
    attributes: Attributes;
}

export interface Attributes {
    isLocked?:             boolean;
    name:                  string;
    authorizedDate?:       string;
    id?:                   number;
    resourceCreatedDate?:  string;
    resourceModifiedDate?: string;
    revisedDate?:          string;
}
